### ISSUE TITLE
Model parameters

### ISSUE THREAD

**Issue by emojiface-ops** [vfa-tranhv/MobileAILab-HairColor-iOS#2]
Hey, great example app, thanks for posting! Your model's accuracy is really impressive. I'm trying to train the model like yours and not getting anywhere near the same accuracy. Mine is 224x224 and alpha=0.5. Using (https://github.com/akirasosa/mobile-semantic-segmentation), I tried running train_full.py on the LFW dataset, with default parameters. I also tried starting with "mobilenet_1_0_224_tf_no_top.h5", training using train_top_model.py, then train_fine_tune.py. Still poor accuracy. How'd you do it?! :)

[Also, your model is 6MB and mine is 24.2MB (!)]

**Comment by akirasosa** [comment]
@emojiface-ops 
May I see your code and commands to reproduce it?

**Comment by emojiface-ops** [comment]
Here's what I did, starting with akirasosa's code:

1. Changed alpha_up to 0.5
  a) In train_top_model.py and train_fine_tune.py, changed:
      "model = MobileUNet(input_shape=(img_height, img_width, 3), alpha_up=0.25)" to "model = MobileUNet(input_shape=(img_height, img_width, 3), alpha_up=0.5)"

2. Downloaded mobile-net weights trained on ImageNet
  a) From here: https://github.com/fchollet/deep-learning-models/releases
  b) The file: mobilenet_1_0_224_tf_no_top.h5

3. Generated npy files by running: python data.py --img_size=224

4. Ran python train_top_model.py --img_file=data/images.npy --mask_file=data/masks.npy --mobilenet_weights_path=mobilenet_1_0_224_tf_no_top.h5

5. After that training is complete, ran: python train_fine_tune.py

**Comment by akirasosa** [comment]
Hi @emojiface-ops ,

Could you try train_full.py ? I usually use it.

**Comment by emojiface-ops** [comment]
I also tried that, got a worse result than yours :). Is that how you trained the model included in this project? Maybe you could post the steps if there was anything special about your approach?

**Comment by akirasosa** [comment]
@emojiface-ops 
There's no special approach. I just do what is written on README.

**Comment by emojiface-ops** [comment]
Ok -- so you just ran the train_full.py in order to produce the "mu_224_050_best2.mlmodel" file in this project? It's odd that yours is so much smaller, but maybe I'm making a mistake in following the directions, I'll re-check my work.

**Comment by akirasosa** [comment]
Yes. It will give enough result. If you want, you can configure alpha and image size. It may give you better result .

**Comment by emojiface-ops** [comment]
Thanks for your responses, I'll keep working on it. Much appreciated!

**Comment by emojiface-ops** [comment]
Hi akirasosa, I'm pretty stumped here. Attached is a comparison of my model (mymodel.jpg) and your model (yourmodel.jpg). Although the beard is confusing it a little, your model is far superior at segmenting the hair. 

We can't be using the same approach because my h5 file is 48.7MB, and my mlmodel file is 24.2MB whereas your mlmodel file is ~6MB.

So here's all the steps, maybe I'm missing something?
1. Downloaded [Labeled Faces in the Wild (LFW)](http://vis-www.cs.umass.edu/lfw/part_labels/) funneled images, all 2927.
2. Downloaded Labeled Faces in the Wild (LFW) Parts Ground Truth Images as gzipped tar file (6MB)... believe these are the same as the ones you posted on Google Drive
3. Renamed all the files using your naming convention *0001.jpg / *0001.ppm
4. Ran data.py --img_size=224; this creates two npy files that are 440.6MB each
5. Modified train_full.py to change alpha_up to 0.5:
    model = MobileUNet(input_shape=(img_height, img_width, 3),
                       alpha=1,
                       alpha_up=0.5)
6. Ran train_full.py
7. Ran coreml-converter.py, got an mlmodel file that's 24.2MB
8. Added the mlmodel to your XCode project, changed the code to use it, and ran on my phone

I can't figure out why our model files are such different sizes. Is there any possibility you used different settings than the default (250 epochs, 16 batch size)? Maybe you can check the interim sizes of some of your files to see if they match mine?

Thanks a million :)

![mymodel](https://user-images.githubusercontent.com/23664055/33870855-bede3bea-dec4-11e7-885e-e663e0cdb6cb.jpg)
![yourmodel](https://user-images.githubusercontent.com/23664055/33870857-bef85552-dec4-11e7-83ce-64606a8e72b5.jpg)

**Comment by emojiface-ops** [comment]
Hi akirasosa, I'm pretty stumped here. Attached is a comparison of my model (mymodel.jpg) and your model (yourmodel.jpg). Although the beard is confusing it a little, your model is far superior at segmenting the hair.

We can't be using the same approach because my h5 file is 48.7MB, and my mlmodel file is 24.2MB whereas your mlmodel file is ~6MB.

So here's all the steps, maybe I'm missing something?

1. Downloaded Labeled Faces in the Wild (LFW) funneled images, all 2927.
2. Downloaded Labeled Faces in the Wild (LFW) Parts Ground Truth Images as gzipped tar file (6MB)... believe these are the same as the ones you posted on Google Drive
3. Renamed all the files using your naming convention *0001.jpg / *0001.ppm
4. Ran data.py --img_size=224; this creates two npy files that are 440.6MB each
5. Modified train_full.py to change alpha_up to 0.5:
    model = MobileUNet(input_shape=(img_height, img_width, 3),
        alpha=1,
        alpha_up=0.5)
6. Ran train_full.py
7. Ran coreml-converter.py, got an mlmodel file that's 24.2MB
8. Added the mlmodel to your XCode project, changed the code to use it, and ran on my phone

I can't figure out why our model files are such different sizes. Is there any possibility you used different settings than the default (250 epochs, 16 batch size)? Maybe you can check the interim sizes of some of your files to see if they match mine?

Thanks a million :)

**Comment by akirasosa** [comment]
@emojiface-ops 
The model in this project uses alpha=0.5 and alpha_up=0.5. Your model uses alpha=1, it would be the reason of different size.

May I ask your training log such as dice loss?

And it's better to check model in python at first, not iOS, to avoid mistake in iOS implementation.

**Comment by emojiface-ops** [comment]
Ah! Thank you! That could be the issue. I'll re-run and if there's still an issue will send you the training log.

**Comment by emojiface-ops** [comment]
The good news is my model is exactly the same size as yours now :). The bad news is it still segments poorly. Attached is the training log. Any ideas?
[training.txt](https://github.com/vfa-tranhv/MobileAILab-HairColor-iOS/files/1553984/training.txt)

**Comment by akirasosa** [comment]
Your dice loss is very low. You should debug each steps. For example, the set of image and mask is corresponding or not.

**Comment by emojiface-ops** [comment]
Hi akirasosa, I figured out the problem. In data.py, these two lines are adding files to the glob in an undefined order:
```
img_files = glob(data_dir + '/images/*.jpg')
mask_files = glob(data_dir + '/masks/*.ppm')
```

Changing them to this fixes my segmentation:
```
img_files = sorted(glob(data_dir + '/images/*.jpg'))
mask_files = sorted(glob(data_dir + '/masks/*.ppm'))
```

I also created a file called download-data.py that automatically downloads images and masks from LFW and organizes them correctly. I created a new branch with these changes, but I can't sync without permission. Could you give permission so I can do a pull request?

Thanks!
Dan

**Comment by akirasosa** [comment]
@emojiface-ops 
You can fork akirasosa/mobile-semantic-segmentation . After that you can create a pull request without any permission.
Thanks!

**Comment by emojiface-ops** [comment]
Will do, thanks.
